kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ required "a valid name is required" .Values.name }}-nw-policy
spec:
  podSelector:
    matchLabels:
      app: {{ required "a valid name is required" .Values.name }}
  ingress:
    - ports:
        - protocol: TCP
          port: 8443
        - protocol: TCP
          port: 8080