apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ required "a valid name is required" .Values.name }}-pull-secret
  labels:
    app: {{ required "a valid name is required" .Values.name }}
    app.kubernetes.io/name: {{ required "a valid name is required" .Values.name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    helm.sh/chart-name: "{{ .Chart.Name }}"
    helm.sh/chart-version: "{{ .Chart.Version }}"
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
