openshift:
  cluster_host: apps.devv3.clusters.adcubum.com
  cluster_project: team-taam-dev

apiVersion: v2

version: 0.1.0-local
name: helm-chart-test
appVersion: "0.1.0-local"
description: "Description"

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
replicas: 1

resources:
  limits:
    cpu: 1000m
    memory: 2048M
  requests:
    cpu: 100m
    memory: 256M

container:
  image:
    registry: adcubum.adcr.io/
    name: taam/taam-config-server
